######################################################################
# Automatically generated by qmake (3.0) lun mag 7 14:36:11 2018
######################################################################

TEMPLATE = app
TARGET = test
INCLUDEPATH += .
QT += widgets

# Input
SOURCES += main.cpp
