######################################################################
# Automatically generated by qmake (3.1) Mon May 28 16:54:57 2018
######################################################################

TEMPLATE = app
TARGET = "testing controller view"
INCLUDEPATH += .
QT += widgets

# The following define makes your compiler warn you if you use any
# feature of Qt which has been marked as deprecated (the exact warnings
# depend on your compiler). Please consult the documentation of the
# deprecated API in order to know how to port your code away from it.
DEFINES += QT_DEPRECATED_WARNINGS

# You can also make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

# Input
HEADERS += Controller/controller.h \
           Controller/session_buffer.h \
           View/KalkButton.h \
           View/startup_view.h \
           "View/specialized view hierarchy/specialized_view.h" \
           "View/specialized view hierarchy/VCircuit.h" \
           "View/specialized view hierarchy/VComplex.h" \
           "View/specialized view hierarchy/VNota.h" \
           "View/specialized view hierarchy/VNumTypes.h" \
           "View/specialized view hierarchy/VRaz.h"
SOURCES += main.cpp \
           Controller/controller.cpp \
           View/startup_view.cpp \
           "View/specialized view hierarchy/specialized_view.cpp" \
           "View/specialized view hierarchy/VCircuit.cpp" \
           "View/specialized view hierarchy/VComplex.cpp" \
           "View/specialized view hierarchy/VNumTypes.cpp" \
           "View/specialized view hierarchy/VRaz.cpp"
