######################################################################
# Automatically generated by qmake (3.0) Sat Jun 2 17:52:53 2018
######################################################################

TEMPLATE = app
TARGET = raz
INCLUDEPATH += .
QT += widgets

# Input
SOURCES += raz.cpp
