######################################################################
# Automatically generated by qmake (3.0) mer ago 29 11:28:47 2018
######################################################################

TEMPLATE = app
TARGET = View
INCLUDEPATH += .
QT +=widgets

# Input
HEADERS += controller_view.h \
           items/KalkButton.h \
           specialized_view_hierarchy/numerical_insert.h \
           specialized_view_hierarchy/specialized_view.h \
           specialized_view_hierarchy/VCircuito.h \
           specialized_view_hierarchy/VComplesso.h \
           specialized_view_hierarchy/VRazionale.h \
           specialized_view_hierarchy/VTupla.h \
           startup/startup_view.h
SOURCES += controller_view.cpp \
           main.cpp \
           specialized_view_hierarchy/numerical_insert.cpp \
           specialized_view_hierarchy/specialized_view.cpp \
           specialized_view_hierarchy/VCircuito.cpp \
           specialized_view_hierarchy/VComplesso.cpp \
           specialized_view_hierarchy/VRazionale.cpp \
           specialized_view_hierarchy/VTupla.cpp \
           startup/startup_view.cpp
