######################################################################
# Automatically generated by qmake (3.0) ven giu 1 12:31:36 2018
######################################################################

TEMPLATE = app
TARGET = complex
INCLUDEPATH += .
QT += widgets

# Input
SOURCES += complex.cpp
