######################################################################
# Automatically generated by qmake (3.0) gio mag 31 15:39:49 2018
######################################################################

TEMPLATE = app
TARGET = drawings
INCLUDEPATH += .
QT += widgets

# Input
SOURCES += main.cpp
