######################################################################
# Automatically generated by qmake (3.0) gio mag 31 13:44:46 2018
######################################################################

TEMPLATE = app
TARGET = "testing controller view"
INCLUDEPATH += .
QT += widgets

# Input
HEADERS += Controller/controller.h \
           Controller/session_buffer.h \
           View/KalkButton.h \
           View/startup_view.h \
           "View/specialized view hierarchy/specialized_view.h" \
           "View/specialized view hierarchy/VCircuit.h" \
           "View/specialized view hierarchy/VComplex.h" \
           "View/specialized view hierarchy/VNota.h" \
           "View/specialized view hierarchy/VNumTypes.h" \
           "View/specialized view hierarchy/VRaz.h"
SOURCES += main.cpp \
           Controller/controller.cpp \
           View/startup_view.cpp \
           "View/specialized view hierarchy/specialized_view.cpp" \
           "View/specialized view hierarchy/VCircuit.cpp" \
           "View/specialized view hierarchy/VComplex.cpp" \
           "View/specialized view hierarchy/VNumTypes.cpp" \
           "View/specialized view hierarchy/VRaz.cpp"
